# Generated by Django 3.1.7 on 2021-03-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20210318_0819'),
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='from_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='to_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_options',
            field=models.ManyToManyField(related_name='options', through='product.ProductOption', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.storagemethod'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='discountrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='dailyspecialdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='product_allergy',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
