# Generated by Django 3.1.7 on 2021-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210318_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspecialdiscount',
            name='daily_discount_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
